spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC'
    username: '${MYSQL_USERNAME}'
    password: '${MYSQL_PASSWORD}'

security:
  jwt:
    token:
      secret-key: '${JWT_SECRET_KEY}'
      expire-length: '${JWT_EXPIRE_LENGTH}'

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: 'jdbc:mysql://localhost:3306/shopping-cart-dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true'
    username: 'rick'
    password: '12341234'

security:
  jwt:
    token:
      secret-key: 'EkJx9MgvDqsqkG3e1ILjdSuXBWybEaPc'
      expire-length: '3600000'

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/local;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
  h2:
    console:
      enabled: true

security:
  jwt:
    token:
      secret-key: 'secret-key'
      expire-length: '3600000'
